### ISSUE TITLE
privacy api class missing

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-block_bbliveusers#2]
In your block you should be able to implement the null provider class as the block doesn't store any user data. (The local plugin will need to implement a more detailed provider class to cover the details of the user data in the local table.)

**Comment by danmarsden** [comment]
(note this is not a blocker for plugin db approval but would be nice to add.)

**Comment by brunomagalhaes** [comment]
Fixed

**Comment by danmarsden** [comment]
Nice! - FYI that class will cause a fatal error if your plugin is installed in a Moodle 3.3 site because the Moodle 3.3 privacy class is slightly different.

If you don't plan to support Moodle 3.3 then that is fine, but if you want to support Moodle 3.3 you will need to use the polyfill (as documented on the privacy api docs page) or create a different branch in your github repo for Moodle 3.3 and lower.

**Comment by brunomagalhaes** [comment]
We were reading the Privacy API documentation... Can we remove the Privacy Provider for now and fully implement it on the next version?
