### ISSUE TITLE
get_content is called twice.

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-block_bbliveusers#3]
the get_content function is called twice for each block on every page load. 

For this reason you need to build $this->content the first time the function is called, and then the 2nd time it is called you need to check if it is not empty and return it. That way you're not running all that code twice on every page load.

See the example here:
https://github.com/moodle/moodle/blob/master/blocks/html/block_html.php#L56

**Comment by brunomagalhaes** [comment]
Hi Dan,

This verification was already in place. As you can see on line 51 in the block_bbliveusers.php file, the block content is only generated when, and only when, the $this-content is empty, otherwise the method just returns the previous compiled/stored content.

Best,
Bruno

**Comment by danmarsden** [comment]
heh - whoops. reviewing too many plugins at once and reading through the code too fast - Sorry about that! - looks good to me! - feel free to submit again for review when ready and this should be ready to pass! - thanks!
