### ISSUE TITLE
thirdpartylibs.xml missing

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-block_bbliveusers#4]
Sorry - just noticed there's one blocker for this one - you have included the chartist js so need to add a thridpartylibs.xml file with the details - here's an example:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

once you have added that - this should be ready to go!

thanks,

**Comment by brunomagalhaes** [comment]
Hey Dan,

Thank you for pointing it out.

Best,
Bruno
